import type { Coordinate, Spot, SpotSource, SpotSourceId } from '@/lib/types';

/**
 * Curated Hamburg recommendation database for the prototype.
 *
 * Coordinates are real map positions, so distances, the radius circle and the
 * map pins all behave like the actual city. Home sits in Ottensen, which puts
 * Altona and the Elbe on the doorstep, St. Pauli and the Schanze two to three
 * kilometres away, and Winterhude, Barmbek and Wilhelmsburg at the far edge of
 * the 10 km radius.
 */
export const HAMBURG_CENTER: { latitude: number; longitude: number; label: string } = {
  latitude: 53.5506,
  longitude: 9.9933,
  label: 'Hamburg city centre',
};

export const HOME: { latitude: number; longitude: number; label: string } = {
  latitude: 53.5514,
  longitude: 9.9245,
  label: 'Ottensen, Hamburg',
};

/** At Hamburg's latitude: 0.01 lat ≈ 1.11 km, 0.01 lng ≈ 0.66 km. */
const KM_PER_DEG_LAT = 111;
const KM_PER_DEG_LNG = 66.2;

/** Used for simulated people, so they scatter around Ottensen realistically. */
export function offsetFromHome(northKm: number, eastKm: number): Coordinate {
  return {
    latitude: HOME.latitude + northKm / KM_PER_DEG_LAT,
    longitude: HOME.longitude + eastKm / KM_PER_DEG_LNG,
  };
}

function at(latitude: number, longitude: number): Coordinate {
  return { latitude, longitude };
}

/** Where the tips come from, shown as a small credit line on every card. */
export const SPOT_SOURCES: Record<SpotSourceId, SpotSource> = {
  geheimtipp: {
    id: 'geheimtipp',
    label: 'Geheimtipp Hamburg',
    blurb: 'Small places locals keep to themselves',
    url: 'https://geheimtipphamburg.de/',
  },
  rausgegangen: {
    id: 'rausgegangen',
    label: 'Rausgegangen Hamburg',
    blurb: 'What is on tonight, hour by hour',
    url: 'https://rausgegangen.de/hamburg/',
  },
  mitvergnuegen: {
    id: 'mitvergnuegen',
    label: 'Mit Vergnügen Hamburg',
    blurb: 'City lists, bars and weekend ideas',
    url: 'https://hamburg.mitvergnuegen.com/',
  },
  hamburgde: {
    id: 'hamburgde',
    label: 'hamburg.de Events',
    blurb: 'The official city events calendar',
    url: 'https://www.hamburg.de/kultur/veranstaltungen',
  },
  hamburgtourismus: {
    id: 'hamburgtourismus',
    label: 'Hamburg Tourismus',
    blurb: 'Landmarks, walks and viewpoints',
    url: 'https://www.hamburg-travel.com/see-explore/events/',
  },
  eventbrite: {
    id: 'eventbrite',
    label: 'Eventbrite',
    blurb: 'Ticketed one-off workshops and jams',
    url: 'https://www.eventbrite.com/d/germany--hamburg/events/',
  },
  meetup: {
    id: 'meetup',
    label: 'Meetup',
    blurb: 'Groups that meet again and again',
    url: 'https://www.meetup.com/find/de--hamburg/',
  },
  kreativgesellschaft: {
    id: 'kreativgesellschaft',
    label: 'Hamburg Kreativ Gesellschaft',
    blurb: 'Open studios and maker spaces',
    url: 'https://kreativgesellschaft.org/termine/',
  },
  community: {
    id: 'community',
    label: 'Local clubs & Stadtteilzentren',
    blurb: 'Sports clubs and neighbourhood houses',
  },
};

/** `via Geheimtipp Hamburg` — the credit line for a single spot. */
export function spotSourceCredit(spot: Spot): string {
  return `via ${SPOT_SOURCES[spot.source].label}`;
}

export const HAMBURG_SPOTS: Spot[] = [
  // ── Ottensen, Övelgönne, Altona: right on the doorstep ──────────────────
  {
    id: 'hh-spritzenplatz',
    name: 'Wochenmarkt Spritzenplatz',
    kind: 'place',
    category: 'market',
    tagline: "Ottensen's market square, two minutes away",
    description:
      'Small, unhurried market where the stallholders talk to everyone. Get a coffee and a Fischbrötchen and stand around the flower stall.',
    address: 'Spritzenplatz, Ottensen',
    district: 'Ottensen',
    source: 'geheimtipp',
    meetingHint: 'By the flower stall in the middle of the square',
    location: at(53.5527, 9.928),
    price: 'cheap',
    cuisine: 'Fischbrötchen & market snacks',
    priceTier: '€',
    bubbleTag: 'Neighbours you have walked past for years',
    interests: ['food', 'talks'],
    crowd: 'Prams, pensioners, late risers',
  },
  {
    id: 'hh-kaffeekueche',
    name: 'Kaffeeküche Fischers Allee',
    kind: 'place',
    category: 'cafe',
    tagline: 'One long table, laptops out after five',
    description:
      'Ottensen corner café with a single big table. Order at the counter, say where you are from, and someone will have an opinion about it.',
    address: 'Fischers Allee, Ottensen',
    district: 'Ottensen',
    source: 'geheimtipp',
    meetingHint: 'Far end of the long table, near the window',
    location: at(53.5535, 9.9215),
    price: 'cheap',
    cuisine: 'Filter coffee & Franzbrötchen',
    priceTier: '€',
    bubbleTag: 'Nobody here does your job',
    interests: ['talks', 'food'],
    crowd: 'Mixed ages, easy chatter',
  },
  {
    id: 'hh-langer-tisch',
    name: 'Langer Tisch Ottensen',
    kind: 'place',
    category: 'food',
    tagline: 'Two dishes a day, shared benches',
    description:
      'A tiny Mittagstisch with no reservations and no space to sit alone. You get whatever is cooked and whoever sits down next to you.',
    address: 'Bahrenfelder Straße, Ottensen',
    district: 'Ottensen',
    source: 'mitvergnuegen',
    meetingHint: 'Ask for the bench seats at the back',
    location: at(53.5518, 9.9295),
    price: 'cheap',
    cuisine: 'Daily two-dish menu, veggie option',
    priceTier: '€€',
    bubbleTag: 'You do not choose your table',
    interests: ['food', 'talks'],
    crowd: 'Tradespeople and office escapees',
  },
  {
    id: 'hh-plattenkeller',
    name: 'Plattenkeller Ottensen',
    kind: 'place',
    category: 'music',
    tagline: 'Record shop with a listening sofa',
    description:
      'Basement full of second-hand vinyl and one sofa by the turntable. Hand over a record you like and you will be handed three back.',
    address: 'Ottenser Hauptstraße, Ottensen',
    district: 'Ottensen',
    source: 'geheimtipp',
    meetingHint: 'Downstairs by the listening deck',
    location: at(53.5505, 9.92),
    price: 'free',
    bubbleTag: 'Genres you would never pick',
    interests: ['music', 'talks'],
    crowd: 'Diggers, patient and opinionated',
  },
  {
    id: 'hh-zeise',
    name: 'Zeise Kinos',
    kind: 'place',
    category: 'culture',
    tagline: 'Old shipyard hall, films in the original',
    description:
      'A cinema built into the Zeise propeller factory. The foyer bar is the point: people stay and argue about the film for an hour.',
    address: 'Friedensallee, Ottensen',
    district: 'Ottensen',
    source: 'mitvergnuegen',
    meetingHint: 'Foyer bar under the old machine hall beams',
    location: at(53.5497, 9.9243),
    price: 'mid',
    cuisine: 'Foyer bar, beer & popcorn',
    priceTier: '€€',
    bubbleTag: 'Subtitles and strong opinions',
    interests: ['art', 'talks'],
    crowd: 'Film people who talk afterwards',
  },
  {
    id: 'hh-altonaer-balkon',
    name: 'Altonaer Balkon',
    kind: 'place',
    category: 'outdoors',
    tagline: 'Container ships from a park bench',
    description:
      'A strip of lawn above the harbour where half of Altona watches the ships come in. Sitting down next to someone is completely normal here.',
    address: 'Altonaer Balkon, Altona-Altstadt',
    district: 'Altona-Altstadt',
    source: 'hamburgtourismus',
    meetingHint: 'The benches at the west end, facing the cranes',
    location: at(53.5462, 9.9345),
    price: 'free',
    bubbleTag: 'Ship spotters and picnic strangers',
    interests: ['outdoors', 'talks'],
    crowd: 'Everyone, in all weather',
  },
  {
    id: 'hh-elbstrand',
    name: 'Elbstrand Övelgönne',
    kind: 'place',
    category: 'outdoors',
    tagline: 'Actual sand, actual harbour, no entry fee',
    description:
      'The city beach below the Elbe path. People share blankets, lend bottle openers and shout at passing freighters.',
    address: 'Övelgönne, Elbstrand',
    district: 'Övelgönne',
    source: 'geheimtipp',
    meetingHint: 'On the sand right of the Strandperle steps',
    location: at(53.5443, 9.9105),
    price: 'free',
    bubbleTag: 'Whole city on one beach',
    interests: ['outdoors', 'talks'],
    crowd: 'Beach mixed, loud when it is warm',
  },
  {
    id: 'hh-boulder-bahrenfeld',
    name: 'Boulderhalle Bahrenfeld',
    kind: 'place',
    category: 'sport',
    tagline: 'Climb, fail, get advice from a stranger',
    description:
      'Industrial hall full of problems colour-coded by grade. Nobody climbs alone here for long, because everyone wants to show you the beta.',
    address: 'Bahrenfelder Chaussee, Bahrenfeld',
    district: 'Bahrenfeld',
    source: 'community',
    meetingHint: 'Warm-up wall by the shoe rental',
    location: at(53.562, 9.907),
    price: 'mid',
    bubbleTag: 'Strangers correcting your technique',
    interests: ['sports'],
    crowd: 'Beginners to obsessives, friendly',
  },
  {
    id: 'hh-tischtennis-altona',
    name: 'Tischtennishalle Altona',
    kind: 'place',
    category: 'sport',
    tagline: 'Six tables, winner stays, everyone rotates',
    description:
      'A club hall that opens its doors for drop-in evenings. The rotation rule means you play whoever walked in after you.',
    address: 'Harkortstraße, Altona-Nord',
    district: 'Altona-Nord',
    source: 'community',
    meetingHint: 'Table four, bats hang by the door',
    location: at(53.5605, 9.933),
    price: 'cheap',
    bubbleTag: 'Skill from clueless to scary',
    interests: ['sports', 'games'],
    crowd: 'Loud, competitive, welcoming',
  },

  // ── St. Pauli, Schanze, Karoviertel: two to three kilometres ────────────
  {
    id: 'hh-hafenklang',
    name: 'Hafenklang',
    kind: 'place',
    category: 'music',
    tagline: 'Bands nobody has heard of yet, right on the water',
    description:
      'A concrete box on the Elbe with a bar upstairs. Loud, cheap and full of people who came alone and left in a group.',
    address: 'Große Elbstraße, Altona-Altstadt',
    district: 'Altona-Altstadt',
    source: 'rausgegangen',
    meetingHint: 'Upstairs bar, left of the stage door',
    location: at(53.5452, 9.9375),
    price: 'mid',
    cuisine: 'Club bar, beer & Mate',
    priceTier: '€',
    bubbleTag: 'Music you cannot name yet',
    interests: ['music', 'dance'],
    crowd: 'Scruffy, curious, all ages',
  },
  {
    id: 'hh-fischmarkt',
    name: 'Altonaer Fischmarkt',
    kind: 'place',
    category: 'market',
    tagline: 'Sunday at dawn, shouted at by fishmongers',
    description:
      'The oldest ritual in the city: coffee, brass band in the auction hall, and total strangers agreeing that this was a bad idea.',
    address: 'Große Elbstraße 9, St. Pauli',
    district: 'St. Pauli',
    source: 'hamburgtourismus',
    meetingHint: 'Outside the Fischauktionshalle main doors',
    location: at(53.546, 9.953),
    price: 'cheap',
    cuisine: 'Fischbrötchen & fruit shouting',
    priceTier: '€',
    bubbleTag: 'Night owls meet early birds',
    interests: ['food', 'music'],
    crowd: 'Half still out, half already up',
  },
  {
    id: 'hh-pudel',
    name: 'Golden Pudel Club',
    kind: 'place',
    category: 'bar',
    tagline: 'Wooden shack on the harbour steps',
    description:
      'Tiny, legendary, permanently overfull. The terrace above the Fischmarkt is where the actual conversations happen.',
    address: 'Fischmarkt 27, St. Pauli',
    district: 'St. Pauli',
    source: 'mitvergnuegen',
    meetingHint: 'On the terrace steps, harbour side',
    location: at(53.5464, 9.9517),
    price: 'cheap',
    cuisine: 'Beer, Mate, no menu',
    priceTier: '€',
    bubbleTag: 'Nobody checks who you are',
    interests: ['music', 'talks', 'dance'],
    crowd: 'Everyone from art students to dockers',
  },
  {
    id: 'hh-park-fiction',
    name: 'Park Fiction',
    kind: 'place',
    category: 'outdoors',
    tagline: 'Palm trees, plastic, best sunset in St. Pauli',
    description:
      'A park the neighbourhood designed itself, hanging above the harbour. Ping pong table, fake palms, and a wall everyone sits on.',
    address: 'Antonistraße, St. Pauli',
    district: 'St. Pauli',
    source: 'geheimtipp',
    meetingHint: 'On the low wall by the palm trees',
    location: at(53.5495, 9.958),
    price: 'free',
    bubbleTag: 'Skaters, choirs and dog people at once',
    interests: ['outdoors', 'music', 'talks'],
    crowd: 'Loud and mixed until late',
  },
  {
    id: 'hh-kickerhalle',
    name: 'Kickerhalle St. Pauli',
    kind: 'place',
    category: 'games',
    tagline: 'Table football, doubles drawn by lot',
    description:
      'Eight tables in a back room off the Reeperbahn. Put a coin on the table and you are in the next game with whoever else did.',
    address: 'Paul-Roosen-Straße, St. Pauli',
    district: 'St. Pauli',
    source: 'rausgegangen',
    meetingHint: 'Back room, tables three and four',
    location: at(53.551, 9.9598),
    price: 'cheap',
    cuisine: 'Beer & fries',
    priceTier: '€',
    bubbleTag: 'You get given a partner',
    interests: ['games', 'sports'],
    crowd: 'Competitive, quick to laugh',
  },
  {
    id: 'hh-aurel',
    name: 'Weinbar Aurel',
    kind: 'place',
    category: 'bar',
    tagline: 'Standing room only, so you talk sideways',
    description:
      'A Schanze corner bar with more pavement than interior. Everyone stands, which means conversations start by accident.',
    address: 'Schanzenstraße, Sternschanze',
    district: 'Sternschanze',
    source: 'mitvergnuegen',
    meetingHint: 'Outside on the pavement, left of the door',
    location: at(53.5615, 9.9605),
    price: 'mid',
    cuisine: 'Wine, beer, olives',
    priceTier: '€€',
    bubbleTag: 'Standing next to complete strangers',
    interests: ['talks', 'food'],
    crowd: 'After-work, loud but not late',
  },
  {
    id: 'hh-spielraum',
    name: 'Spielraum Schanze',
    kind: 'place',
    category: 'games',
    tagline: 'Board game café, open tables for singles',
    description:
      'Shelves to the ceiling and a table marked "join here". Staff explain the rules and then leave you to it with three strangers.',
    address: 'Susannenstraße, Sternschanze',
    district: 'Sternschanze',
    source: 'geheimtipp',
    meetingHint: 'The open table by the games shelf',
    location: at(53.5628, 9.9635),
    price: 'cheap',
    cuisine: 'Toasties & lemonade',
    priceTier: '€€',
    bubbleTag: 'Rules explained by strangers',
    interests: ['games', 'talks'],
    crowd: 'Patient, nerdy, kind',
  },
  {
    id: 'hh-thai-schanze',
    name: 'Thai Imbiss Schanzenstraße',
    kind: 'place',
    category: 'food',
    tagline: 'Six stools, one very good curry',
    description:
      'A counter kitchen where the queue is the social event. Ask what to order and three people will answer at once.',
    address: 'Schanzenstraße, Sternschanze',
    district: 'Sternschanze',
    source: 'mitvergnuegen',
    meetingHint: 'In the queue on the pavement',
    location: at(53.5645, 9.9645),
    price: 'cheap',
    cuisine: 'Thai, one long counter',
    priceTier: '€',
    bubbleTag: 'Queue conversations',
    interests: ['food'],
    crowd: 'Fast, hungry, chatty',
  },
  {
    id: 'hh-karo-kueche',
    name: 'Küche für Alle, Karoviertel',
    kind: 'place',
    category: 'food',
    tagline: 'Cook together, pay what you can',
    description:
      'A neighbourhood kitchen where the cooking is the programme. Turn up, get handed a knife, eat with fifteen people you just met.',
    address: 'Marktstraße, Karolinenviertel',
    district: 'Karolinenviertel',
    source: 'community',
    meetingHint: 'Kitchen door in the courtyard',
    location: at(53.5578, 9.966),
    price: 'free',
    cuisine: 'Vegetarian, cooked together',
    priceTier: '€',
    bubbleTag: 'Nobody arrives as a guest',
    interests: ['food', 'talks'],
    crowd: 'Warm, chaotic, all backgrounds',
  },

  // ── Neustadt, Altstadt, HafenCity: four to six kilometres ───────────────
  {
    id: 'hh-planten-un-blomen',
    name: 'Planten un Blomen',
    kind: 'place',
    category: 'outdoors',
    tagline: 'City park with a lake and a bandstand',
    description:
      "Hamburg's big central garden. Deck chairs, a rose garden and an open lawn where groups form around whoever brought a ball.",
    address: 'Planten un Blomen, Neustadt',
    district: 'Neustadt',
    source: 'hamburgtourismus',
    meetingHint: 'By the water-organ lake, east side',
    location: at(53.5598, 9.98),
    price: 'free',
    bubbleTag: 'Lawn strangers and brass bands',
    interests: ['outdoors', 'music'],
    crowd: 'Families, students, sunbathers',
  },
  {
    id: 'hh-gaengeviertel',
    name: 'Gängeviertel Werkstätten',
    kind: 'place',
    category: 'craft',
    tagline: 'Squatted quarter turned open workshop',
    description:
      'The last old Hamburg alleys, saved by artists. Print, wood and repair workshops with open evenings and no membership.',
    address: 'Valentinskamp, Neustadt',
    district: 'Neustadt',
    source: 'kreativgesellschaft',
    meetingHint: 'Courtyard between Fabrique and Jupi',
    location: at(53.5565, 9.9822),
    price: 'cheap',
    bubbleTag: 'Hands dirty within ten minutes',
    interests: ['art', 'talks'],
    crowd: 'Makers, activists, curious visitors',
  },
  {
    id: 'hh-kanu-speicherstadt',
    name: 'Kanuverleih Speicherstadt',
    kind: 'place',
    category: 'sport',
    tagline: 'Paddle the canals between the warehouses',
    description:
      'Two-seater canoes into the Fleete. You share a boat, so you either learn to coordinate with a stranger or you go in circles.',
    address: 'Holzbrücke, HafenCity',
    district: 'HafenCity',
    source: 'hamburgde',
    meetingHint: 'Pontoon under the Holzbrücke',
    location: at(53.5437, 9.9915),
    price: 'mid',
    bubbleTag: 'Forced teamwork on water',
    interests: ['sports', 'outdoors'],
    crowd: 'Nervous first-timers, mostly',
  },
  {
    id: 'hh-kunsthalle',
    name: 'Hamburger Kunsthalle',
    kind: 'place',
    category: 'culture',
    tagline: 'Late opening, one room at a time',
    description:
      'Three connected buildings from old masters to contemporary. On late evenings the café turns into an accidental discussion group.',
    address: 'Glockengießerwall, Altstadt',
    district: 'Altstadt',
    source: 'hamburgtourismus',
    meetingHint: 'Café in the Galerie der Gegenwart',
    location: at(53.5548, 10.0),
    price: 'mid',
    cuisine: 'Museum café',
    priceTier: '€€',
    bubbleTag: 'Art you would not have chosen',
    interests: ['art', 'talks'],
    crowd: 'Quiet, then very talkative',
  },
  {
    id: 'hh-oberhafen',
    name: 'Oberhafen-Quartier',
    kind: 'place',
    category: 'culture',
    tagline: 'Freight halls full of studios and one big kitchen',
    description:
      'A goods station handed to artists and cooks. Concerts, workshops and long tables between the rails, with the skyline behind.',
    address: 'Stockmeyerstraße, HafenCity',
    district: 'HafenCity',
    source: 'kreativgesellschaft',
    meetingHint: 'Between Halle 424 and the canteen',
    location: at(53.5427, 10.0055),
    price: 'cheap',
    cuisine: 'Canteen plates, changing daily',
    priceTier: '€€',
    bubbleTag: 'Everyone is here for something different',
    interests: ['art', 'music', 'food'],
    crowd: 'Studios, skaters, curious wanderers',
  },

  // ── Eimsbüttel and Hoheluft ─────────────────────────────────────────────
  {
    id: 'hh-nachbarschaftscafe',
    name: 'Nachbarschaftscafé Eimsbüttel',
    kind: 'place',
    category: 'cafe',
    tagline: 'Bottomless coffee, run by volunteers',
    description:
      'A neighbourhood café in a Stadtteilzentrum. Cake, board games and a rule that nobody sits alone unless they want to.',
    address: 'Osterstraße, Eimsbüttel',
    district: 'Eimsbüttel',
    source: 'community',
    meetingHint: 'Big round table near the counter',
    location: at(53.5745, 9.956),
    price: 'cheap',
    cuisine: 'Cake, soup, endless coffee',
    priceTier: '€',
    bubbleTag: 'Ages eighteen to eighty at one table',
    interests: ['talks', 'games', 'food'],
    crowd: 'Regulars who adopt newcomers',
  },
  {
    id: 'hh-kaifu',
    name: 'Kaifu-Bad Abendschwimmen',
    kind: 'place',
    category: 'sport',
    tagline: 'Lane swimming, then the sauna bench',
    description:
      'The old Eimsbüttel baths with evening lanes. Swim as long as you like; the actual conversations happen in the queue for a hairdryer.',
    address: 'Hohe Weide, Eimsbüttel',
    district: 'Eimsbüttel',
    source: 'community',
    meetingHint: 'Entrance hall by the ticket window',
    location: at(53.5762, 9.9662),
    price: 'cheap',
    bubbleTag: 'Nobody is dressed to impress',
    interests: ['sports'],
    crowd: 'Steady swimmers, no rush',
  },

  // ── Winterhude, Barmbek: six to eight kilometres ────────────────────────
  {
    id: 'hh-goldbekhaus',
    name: 'Goldbekhaus Werkstatt',
    kind: 'place',
    category: 'craft',
    tagline: 'Community house with tools on the wall',
    description:
      'Courses, repair evenings and a canal-side terrace. You bring something broken, someone shows you how to fix it.',
    address: 'Moorfuhrtweg, Winterhude',
    district: 'Winterhude',
    source: 'community',
    meetingHint: 'Workshop room, ground floor left',
    location: at(53.5877, 10.0122),
    price: 'cheap',
    bubbleTag: 'Skills swapped, not sold',
    interests: ['art', 'talks'],
    crowd: 'Handy, patient, generous',
  },
  {
    id: 'hh-kampnagel',
    name: 'Kampnagel',
    kind: 'place',
    category: 'culture',
    tagline: 'Crane factory turned performance halls',
    description:
      'International theatre and dance in raw industrial halls, with a courtyard bar that keeps going long after the show.',
    address: 'Jarrestraße, Winterhude',
    district: 'Winterhude',
    source: 'rausgegangen',
    meetingHint: 'Courtyard bar between K6 and the kiosk',
    location: at(53.583, 10.018),
    price: 'mid',
    cuisine: 'Courtyard bar & snacks',
    priceTier: '€€',
    bubbleTag: 'Nothing you can explain afterwards',
    interests: ['art', 'dance', 'music'],
    crowd: 'Theatre crowd, unusually open',
  },
  {
    id: 'hh-stadtpark',
    name: 'Stadtpark Große Wiese',
    kind: 'place',
    category: 'outdoors',
    tagline: 'One enormous lawn, everyone on it',
    description:
      "The city's back garden: football, slacklines, drum circles and swimming in the Naturbad. Joining a game is normal here.",
    address: 'Hamburger Stadtpark, Winterhude',
    district: 'Winterhude',
    source: 'hamburgde',
    meetingHint: 'Big lawn in front of the Planetarium',
    location: at(53.5945, 10.0165),
    price: 'free',
    bubbleTag: 'Twenty games happening at once',
    interests: ['outdoors', 'sports', 'music'],
    crowd: 'Whole city on a sunny day',
  },

  // ── Wilhelmsburg: over the Elbe ─────────────────────────────────────────
  {
    id: 'hh-honigfabrik',
    name: 'Honigfabrik',
    kind: 'place',
    category: 'culture',
    tagline: 'Old factory run by the neighbourhood',
    description:
      'Concerts, workshops and a café in a building the island organises itself. The least polished, friendliest room in Hamburg.',
    address: 'Industriestraße, Wilhelmsburg',
    district: 'Wilhelmsburg',
    source: 'kreativgesellschaft',
    meetingHint: 'Café by the main entrance',
    location: at(53.4995, 9.9945),
    price: 'cheap',
    cuisine: 'Café plates, cheap and hearty',
    priceTier: '€',
    bubbleTag: 'An island you never visit',
    interests: ['music', 'art', 'talks'],
    crowd: 'Islanders, students, families',
  },
  {
    id: 'hh-inselpark',
    name: 'Inselpark Wilhelmsburg',
    kind: 'place',
    category: 'sport',
    tagline: 'Climbing hall, skate bowl, open pitches',
    description:
      'A former garden-show park with sport everywhere: bouldering, basketball, skating. Pitches are shared by whoever turns up.',
    address: 'Inselparkallee, Wilhelmsburg',
    district: 'Wilhelmsburg',
    source: 'community',
    meetingHint: 'By the climbing hall entrance',
    location: at(53.493, 10.005),
    price: 'cheap',
    bubbleTag: 'Teams picked on the spot',
    interests: ['sports', 'outdoors'],
    crowd: 'Young, mixed, competitive',
  },

  // ── Events: today only, with a window ──────────────────────────────────
  {
    id: 'hh-event-elbe-run',
    name: 'Slow 5k along the Elbe',
    kind: 'event',
    category: 'sport',
    tagline: 'Deliberately slow so you can talk',
    description:
      'A running group that starts at the Elbe path and goes at chatting pace. Nobody is dropped, nobody times you.',
    address: 'Övelgönne, start at the Strandperle steps',
    district: 'Övelgönne',
    source: 'meetup',
    meetingHint: 'At the steps down to the beach',
    location: at(53.545, 9.906),
    startsInMinutes: 35,
    runsForMinutes: 75,
    price: 'free',
    bubbleTag: 'Talking is the point, not the pace',
    interests: ['sports', 'outdoors'],
    crowd: 'Chatty runners, zero elitism',
  },
  {
    id: 'hh-event-flohschanze',
    name: 'Flohschanze flea market',
    kind: 'event',
    category: 'market',
    tagline: 'Saturday junk, bartering encouraged',
    description:
      'The Schanze flea market in the old cattle hall yard. Haggling is a conversation, and half the stalls will just tell you the story instead.',
    address: 'Neuer Kamp 30, Sternschanze',
    district: 'Sternschanze',
    source: 'geheimtipp',
    meetingHint: 'Under the arch at the Neuer Kamp entrance',
    location: at(53.5588, 9.9678),
    startsInMinutes: 45,
    runsForMinutes: 300,
    price: 'cheap',
    cuisine: 'Coffee carts & waffles',
    priceTier: '€',
    bubbleTag: "Objects with strangers' stories attached",
    interests: ['art', 'talks'],
    crowd: 'Early hunters, then everyone',
  },
  {
    id: 'hh-event-sprachcafe',
    name: 'Sprachcafé: swap a language',
    kind: 'event',
    category: 'cafe',
    tagline: 'Half an hour your language, half an hour theirs',
    description:
      'Volunteers pair people up by language. You will be speaking to a total stranger within four minutes, which is the whole idea.',
    address: 'Stadtteilzentrum Osterstraße, Eimsbüttel',
    district: 'Eimsbüttel',
    source: 'community',
    meetingHint: 'Sign-in desk at the café entrance',
    location: at(53.5747, 9.9552),
    startsInMinutes: 55,
    runsForMinutes: 120,
    price: 'free',
    cuisine: 'Tea & cake, donation box',
    priceTier: '€',
    bubbleTag: 'Paired with someone at random',
    interests: ['talks'],
    crowd: 'Newcomers and locals, mixed',
  },
  {
    id: 'hh-event-beachvolley',
    name: 'Beach volleyball, mixed teams',
    kind: 'event',
    category: 'sport',
    tagline: 'Teams drawn from whoever shows up',
    description:
      'Courts on the Elbe sand, teams reshuffled every two sets. Bring nothing, borrow everything.',
    address: 'Beachplatz Övelgönne, Elbstrand',
    district: 'Övelgönne',
    source: 'community',
    meetingHint: 'Court two, by the net bag',
    location: at(53.544, 9.913),
    startsInMinutes: 60,
    runsForMinutes: 120,
    price: 'cheap',
    bubbleTag: 'You never keep the same team',
    interests: ['sports', 'outdoors'],
    crowd: 'Sporty but forgiving',
  },
  {
    id: 'hh-event-salsa-alster',
    name: 'Beginner salsa by the Alster',
    kind: 'event',
    category: 'outdoors',
    tagline: 'Free class, then everybody rotates',
    description:
      'Open-air steps on the Alster promenade. The rotation means you dance with a dozen people and remember none of the names.',
    address: 'Alsterufer, Neustadt',
    district: 'Neustadt',
    source: 'meetup',
    meetingHint: 'Promenade level, by the boat jetty',
    location: at(53.5545, 9.993),
    startsInMinutes: 70,
    runsForMinutes: 90,
    price: 'free',
    bubbleTag: 'Physical contact with strangers, immediately',
    interests: ['dance', 'music'],
    crowd: 'Beginners laughing at themselves',
  },
  {
    id: 'hh-event-hafenrundgang',
    name: 'Harbour walk with a local guide',
    kind: 'event',
    category: 'culture',
    tagline: 'Ninety minutes, tips only',
    description:
      'A walk from Landungsbrücken through the old harbour streets. Small group, lots of questions, ends at a kiosk.',
    address: 'Landungsbrücken, Brücke 3, St. Pauli',
    district: 'St. Pauli',
    source: 'hamburgtourismus',
    meetingHint: 'Under the clock tower at Brücke 3',
    location: at(53.5455, 9.969),
    startsInMinutes: 80,
    runsForMinutes: 90,
    price: 'free',
    bubbleTag: 'Your own city, explained',
    interests: ['talks', 'outdoors'],
    crowd: 'Curious locals and a few visitors',
  },
  {
    id: 'hh-event-feierabendmarkt',
    name: 'Feierabendmarkt Ottensen',
    kind: 'event',
    category: 'market',
    tagline: 'Street food stands, beer crates as tables',
    description:
      'Evening market on the square with a dozen stands and nowhere private to sit. Crates fill up in strangers-with-plates formation.',
    address: 'Alma-Wartenberg-Platz, Ottensen',
    district: 'Ottensen',
    source: 'hamburgde',
    meetingHint: 'By the crates in front of the bakery',
    location: at(53.5532, 9.931),
    startsInMinutes: 90,
    runsForMinutes: 180,
    price: 'cheap',
    cuisine: 'Street food stands',
    priceTier: '€€',
    bubbleTag: 'One crate, four strangers',
    interests: ['food', 'music', 'talks'],
    crowd: 'After-work Ottensen, all ages',
  },
  {
    id: 'hh-event-quiz-schanze',
    name: 'Pub quiz, teams drawn at random',
    kind: 'event',
    category: 'bar',
    tagline: 'Arrive alone, get put on a team',
    description:
      'Schanze pub quiz where singles are drawn into teams from a hat. Six rounds, one of them always about Hamburg.',
    address: 'Schulterblatt, Sternschanze',
    district: 'Sternschanze',
    source: 'mitvergnuegen',
    meetingHint: 'Back room, ask for the singles table',
    location: at(53.562, 9.962),
    startsInMinutes: 105,
    runsForMinutes: 150,
    price: 'cheap',
    cuisine: 'Pub food & beer',
    priceTier: '€€',
    bubbleTag: 'Your team is assigned to you',
    interests: ['games', 'talks'],
    crowd: 'Loud, silly, quick friends',
  },
  {
    id: 'hh-event-sunset-yoga',
    name: 'Sunset yoga at Park Fiction',
    kind: 'event',
    category: 'outdoors',
    tagline: 'Mats between the fake palms',
    description:
      'Donation-based class facing the harbour cranes. The container ships are the soundtrack and nobody watches your form.',
    address: 'Park Fiction, St. Pauli',
    district: 'St. Pauli',
    source: 'eventbrite',
    meetingHint: 'Upper terrace, by the palm trees',
    location: at(53.5497, 9.9578),
    startsInMinutes: 115,
    runsForMinutes: 75,
    price: 'cheap',
    bubbleTag: 'Everyone is equally wobbly',
    interests: ['sports', 'outdoors'],
    crowd: 'Calm, mixed, unpretentious',
  },
  {
    id: 'hh-event-oberhafen-studio',
    name: 'Open studio night, Oberhafen',
    kind: 'event',
    category: 'craft',
    tagline: 'Doors open, tools free, ask anything',
    description:
      'Print, ceramics and wood studios in the freight halls open up for the evening. Makers explain what they are doing to whoever walks in.',
    address: 'Halle 424, Stockmeyerstraße, HafenCity',
    district: 'HafenCity',
    source: 'kreativgesellschaft',
    meetingHint: 'Halle 424 entrance, follow the rails',
    location: at(53.5429, 10.006),
    startsInMinutes: 125,
    runsForMinutes: 180,
    price: 'free',
    bubbleTag: 'Trades you have never seen up close',
    interests: ['art', 'talks'],
    crowd: 'Makers happy to be interrupted',
  },
  {
    id: 'hh-event-open-stage',
    name: 'Open stage at Hafenklang',
    kind: 'event',
    category: 'music',
    tagline: 'Fifteen acts, eight minutes each',
    description:
      'Sign-up list on the door and no idea what you are about to hear. The bar between sets is where the talking happens.',
    address: 'Große Elbstraße 84, Altona-Altstadt',
    district: 'Altona-Altstadt',
    source: 'rausgegangen',
    meetingHint: 'By the sign-up list at the door',
    location: at(53.5454, 9.9377),
    startsInMinutes: 135,
    runsForMinutes: 180,
    price: 'cheap',
    cuisine: 'Club bar',
    priceTier: '€',
    bubbleTag: 'Nobody knows what comes next',
    interests: ['music', 'talks'],
    crowd: 'Supportive, slightly nervous',
  },
  {
    id: 'hh-event-improv',
    name: 'Improv jam for total beginners',
    kind: 'event',
    category: 'culture',
    tagline: 'No audience, no experience, no lines',
    description:
      'Two hours of games in a Karoviertel rehearsal room. You cannot do this alone, which is exactly why it works.',
    address: 'Probenraum Marktstraße, Karolinenviertel',
    district: 'Karolinenviertel',
    source: 'eventbrite',
    meetingHint: 'First floor, shoes off at the door',
    location: at(53.558, 9.964),
    startsInMinutes: 150,
    runsForMinutes: 120,
    price: 'cheap',
    bubbleTag: 'Everyone is equally bad at this',
    interests: ['talks', 'art'],
    crowd: 'Gentle, funny, self-deprecating',
  },
  {
    id: 'hh-event-repair-goldbek',
    name: 'Repair Café at Goldbekhaus',
    kind: 'event',
    category: 'craft',
    tagline: 'Bring something broken, fix it together',
    description:
      'Volunteers with soldering irons and sewing machines. You do the work, they talk you through it, everyone eats pizza afterwards.',
    address: 'Moorfuhrtweg 9, Winterhude',
    district: 'Winterhude',
    source: 'community',
    meetingHint: 'Workshop room, sign in at the table',
    location: at(53.5879, 10.0126),
    startsInMinutes: 165,
    runsForMinutes: 240,
    price: 'free',
    bubbleTag: 'Strangers with better tools than you',
    interests: ['art', 'talks'],
    crowd: 'Practical, unhurried, all ages',
  },
  {
    id: 'hh-event-kampnagel-late',
    name: 'Kampnagel late: dance floor for beginners',
    kind: 'event',
    category: 'music',
    tagline: 'Short workshop, then the floor opens',
    description:
      'Late-night programme in the factory halls: twenty minutes of instruction, then everyone stays and dances badly together.',
    address: 'Jarrestraße 20, Winterhude',
    district: 'Winterhude',
    source: 'rausgegangen',
    meetingHint: 'Hall K6, follow the courtyard lights',
    location: at(53.5832, 10.0184),
    startsInMinutes: 190,
    runsForMinutes: 210,
    price: 'mid',
    cuisine: 'Courtyard bar',
    priceTier: '€€',
    bubbleTag: 'Dancing with people you cannot see',
    interests: ['dance', 'music'],
    crowd: 'Late, warm, uninhibited',
  },
  {
    id: 'hh-event-honigfabrik-konzert',
    name: 'Island concert at Honigfabrik',
    kind: 'event',
    category: 'music',
    tagline: 'Two bands from Wilhelmsburg, five euros',
    description:
      'Neighbourhood concert in the old factory hall. Half the audience knows the band, and by the end the other half does too.',
    address: 'Industriestraße 125, Wilhelmsburg',
    district: 'Wilhelmsburg',
    source: 'hamburgde',
    meetingHint: 'Main hall, right of the sound desk',
    location: at(53.4997, 9.9949),
    startsInMinutes: 205,
    runsForMinutes: 180,
    price: 'cheap',
    cuisine: 'Bar, cheap beer',
    priceTier: '€',
    bubbleTag: 'A part of town you never cross to',
    interests: ['music', 'talks'],
    crowd: 'Islanders, loyal and loud',
  },
];
