import type { Interest, Person, Spot } from '@/lib/types';

/** Everything time-based is relative to when the app session started. */
export const SESSION_START = Date.now();

export const HOME: { latitude: number; longitude: number; label: string } = {
  latitude: 52.4996,
  longitude: 13.4232,
  label: 'Kreuzberg, Berlin',
};

/** 0.01 lat ≈ 1.11 km, 0.01 lng ≈ 0.68 km at this latitude. */
function offset(northKm: number, eastKm: number) {
  return {
    latitude: HOME.latitude + northKm / 111,
    longitude: HOME.longitude + eastKm / 67.8,
  };
}

export const INTEREST_LABELS: Record<Interest, string> = {
  music: 'Music',
  sports: 'Sports',
  food: 'Food',
  art: 'Art',
  outdoors: 'Outdoors',
  games: 'Games',
  talks: 'Talks',
  dance: 'Dance',
};

export const ALL_INTERESTS: Interest[] = [
  'music',
  'sports',
  'food',
  'art',
  'outdoors',
  'games',
  'talks',
  'dance',
];

export const SPOTS: Spot[] = [
  {
    id: 'spot-kollektiv',
    name: 'Café Kollektiv',
    kind: 'place',
    category: 'cafe',
    tagline: 'Long shared table, no laptops after 6',
    description:
      'One big oak table where sitting alone is basically an invitation. The staff introduce people who order the same thing.',
    address: 'Reichenberger Str. 74',
    meetingHint: 'Grab the far end of the long table by the window',
    location: offset(0.3, 0.5),
    price: 'cheap',
    bubbleTag: 'Nobody here works in your field',
    interests: ['talks', 'food'],
    crowd: 'Mixed ages, easy chatter',
  },
  {
    id: 'spot-pingpong',
    name: 'Kiezklub Ping Pong Hall',
    kind: 'place',
    category: 'sport',
    tagline: 'Round-the-table games, winner stays',
    description:
      'Six tables, one rule: you rotate. You end up playing with whoever walked in two minutes after you.',
    address: 'Wiener Str. 12',
    meetingHint: 'Table 4, rackets are on the wall',
    location: offset(-0.6, 1.0),
    price: 'cheap',
    bubbleTag: 'Skill levels from clueless to scary',
    interests: ['sports', 'games'],
    crowd: 'Loud, competitive, friendly',
  },
  {
    id: 'spot-feld',
    name: 'Tempelhofer Feld Sunset Ridge',
    kind: 'place',
    category: 'outdoors',
    tagline: 'Old runway, best light in the city',
    description:
      'Bring something to sit on. Strangers share blankets here more than anywhere else in Berlin.',
    address: 'Tempelhofer Feld, north entrance',
    meetingHint: 'On the grass strip right of the north gate',
    location: offset(-1.4, -2.2),
    price: 'free',
    bubbleTag: 'Kite people, skaters, choirs, all at once',
    interests: ['outdoors', 'talks'],
    crowd: 'Everyone in the city, honestly',
  },
  {
    id: 'spot-wuerfel',
    name: 'Brettspiel Bar Würfel',
    kind: 'place',
    category: 'games',
    tagline: '400 board games, tables for strangers',
    description:
      'A shelf marked "easy to teach". Sit at a green-flag table and someone will explain the rules to you.',
    address: 'Oranienstr. 190',
    meetingHint: 'Green-flag table near the game shelf',
    location: offset(0.9, -1.4),
    price: 'cheap',
    bubbleTag: 'Green-flag tables are for open groups only',
    interests: ['games', 'talks'],
    crowd: 'Nerdy in the warmest way',
  },
  {
    id: 'spot-karaoke',
    name: 'Karaoke Keller Sonntag',
    kind: 'place',
    category: 'music',
    tagline: 'Basement, one mic, zero judgement',
    description: 'You will sing a duet with someone you have never met. That is just how it goes.',
    address: 'Skalitzer Str. 134',
    meetingHint: 'Bottom of the stairs, sign-up clipboard',
    location: offset(1.8, 2.6),
    price: 'cheap',
    bubbleTag: 'Duets are assigned, not chosen',
    interests: ['music', 'dance'],
    crowd: 'Brave and slightly off-key',
  },
  {
    id: 'spot-markthalle',
    name: 'Markthalle Neun',
    kind: 'place',
    category: 'market',
    tagline: 'Street food hall, communal benches',
    description:
      'Twenty kitchens, shared benches. Order something you cannot pronounce and split it.',
    address: 'Eisenbahnstr. 42',
    meetingHint: 'Middle bench under the big clock',
    location: offset(0.5, -0.6),
    price: 'mid',
    bubbleTag: 'Everyone shares a table by default',
    interests: ['food', 'talks'],
    crowd: 'Families, tourists, locals',
  },
  {
    id: 'spot-boulder',
    name: 'Boulder Base Ost',
    kind: 'place',
    category: 'sport',
    tagline: 'Bouldering, no partner needed',
    description:
      'The one sport where people spontaneously coach each other. Shoe rental at the desk.',
    address: 'Modersohnstr. 8',
    meetingHint: 'Beginner wall, left of the entrance',
    location: offset(3.4, 2.7),
    price: 'mid',
    bubbleTag: 'Strangers hand out advice constantly',
    interests: ['sports'],
    crowd: 'Chalky, chatty, patient',
  },
  {
    id: 'spot-rille',
    name: 'Rille Records Listening Room',
    kind: 'place',
    category: 'music',
    tagline: 'Bring a record, play one side',
    description: 'A sofa, a good system, and a rule that everyone plays one track they love.',
    address: 'Manteuffelstr. 90',
    meetingHint: 'Back room sofa, past the crates',
    location: offset(1.2, 1.3),
    price: 'free',
    bubbleTag: 'You will hear music you would never pick',
    interests: ['music', 'talks'],
    crowd: 'Quiet listeners, strong opinions',
  },
  {
    id: 'spot-kueche',
    name: 'Küche für Alle',
    kind: 'place',
    category: 'food',
    tagline: 'Cook together, eat together, pay what you can',
    description:
      'Show up, get handed a knife and a pile of vegetables, meet whoever chops next to you.',
    address: 'Adalbertstr. 4',
    meetingHint: 'Kitchen door in the courtyard',
    location: offset(1.1, -0.9),
    price: 'free',
    bubbleTag: 'Nobody arrives as a guest here',
    interests: ['food', 'talks'],
    crowd: 'Neighbourhood mix, all ages',
  },
  {
    id: 'spot-rooftop',
    name: 'Dachkino Rooftop Cinema',
    kind: 'place',
    category: 'culture',
    tagline: 'Deck chairs, one film, loud opinions after',
    description:
      'The post-film beer on the roof is the actual event. People stay and argue about it.',
    address: 'Prinzenstr. 85, top floor',
    meetingHint: 'Bar on the roof, left of the projector',
    location: offset(2.1, -4.1),
    price: 'mid',
    bubbleTag: 'Film choice is announced only at the door',
    interests: ['art', 'talks'],
    crowd: 'Opinionated, welcoming',
  },
  {
    id: 'event-openmic',
    name: 'Open Mic at Zimmer 16',
    kind: 'event',
    category: 'music',
    tagline: 'Five minutes each, anyone can sign up',
    description:
      'Poetry, guitar, stand-up, one guy with a theremin. Sign-up sheet closes when the first act starts.',
    address: 'Zimmer 16, Görlitzer Str. 16',
    meetingHint: 'Sign-up sheet by the sound desk',
    location: offset(0.9, 1.9),
    startsInMinutes: 95,
    price: 'cheap',
    bubbleTag: 'Performers and audience mix all night',
    interests: ['music', 'art', 'talks'],
    crowd: 'Generous audience, weird acts',
  },
  {
    id: 'event-salsa',
    name: 'Beginner Salsa in the Park',
    kind: 'event',
    category: 'outdoors',
    tagline: 'Free class, rotating partners',
    description: 'Partners rotate every two minutes, so you will dance with the whole circle.',
    address: 'Görlitzer Park, by the bridge',
    meetingHint: 'Under the bridge, follow the speaker',
    location: offset(0.4, 1.4),
    startsInMinutes: 50,
    price: 'free',
    bubbleTag: 'Rotating partners, no experience allowed to matter',
    interests: ['dance', 'outdoors'],
    crowd: 'Nervous beginners, two show-offs',
  },
  {
    id: 'event-repair',
    name: 'Repair Café & Pizza',
    kind: 'event',
    category: 'craft',
    tagline: 'Bring something broken, fix it with a stranger',
    description:
      'Toasters, bikes, lamps, jeans. Volunteers pair you up with whoever knows that particular thing.',
    address: 'Nachbarschaftshaus, Urbanstr. 21',
    meetingHint: 'Front desk, they hand out tool numbers',
    location: offset(-1.1, -1.9),
    startsInMinutes: 130,
    price: 'free',
    bubbleTag: 'You get paired by problem, not by profile',
    interests: ['talks', 'art'],
    crowd: 'Tinkerers, retirees, students',
  },
  {
    id: 'event-quiz',
    name: 'Pub Quiz: Teams of Strangers',
    kind: 'event',
    category: 'bar',
    tagline: 'Teams are drawn at random',
    description: 'You cannot sign up as a group. Names go in a hat and teams of five come out.',
    address: 'Zum Goldenen Hahn, Skalitzer Str. 78',
    meetingHint: 'Team draw happens at the bar',
    location: offset(0.6, 0.3),
    startsInMinutes: 75,
    price: 'cheap',
    bubbleTag: 'Random teams, literally out of a hat',
    interests: ['games', 'talks'],
    crowd: 'Trivia sharks and casuals',
  },
  {
    id: 'event-run',
    name: 'Slow 5k Run Club',
    kind: 'event',
    category: 'sport',
    tagline: 'Conversation pace, nobody left behind',
    description:
      'The whole point is that you can talk while running. Coffee after for whoever wants it.',
    address: 'Landwehrkanal, Lohmühlenbrücke',
    meetingHint: 'North side of the bridge, look for the yellow flag',
    location: offset(-1.5, 1.6),
    startsInMinutes: 35,
    price: 'free',
    bubbleTag: 'Pairs are set by pace, not by who you know',
    interests: ['sports', 'outdoors'],
    crowd: 'Chatty runners, zero elitism',
  },
  {
    id: 'event-drawing',
    name: 'Life Drawing for Absolute Beginners',
    kind: 'event',
    category: 'culture',
    tagline: 'Charcoal provided, talent not required',
    description:
      'Everyone shows their worst drawing at the end. It is the fastest icebreaker there is.',
    address: 'Atelier Süd, Hasenheide 54',
    meetingHint: 'Studio on the first floor, shoes off',
    location: offset(-2.3, -5.2),
    startsInMinutes: 160,
    price: 'cheap',
    bubbleTag: 'Everyone is equally bad at this',
    interests: ['art'],
    crowd: 'Gentle, focused, funny',
  },
];

export function spotStartsAt(spot: Spot): number | undefined {
  return spot.startsInMinutes === undefined
    ? undefined
    : SESSION_START + spot.startsInMinutes * 60_000;
}

export const PEOPLE: Person[] = [
  {
    id: 'p-yara',
    name: 'Yara',
    age: 29,
    bio: 'Night-shift nurse, learning bass badly',
    colorClass: 'bg-berry',
    interests: ['music', 'food'],
    location: offset(0.7, 0.4),
    travelMode: 'bike',
    vibe: 'eager',
  },
  {
    id: 'p-tomas',
    name: 'Tomás',
    age: 34,
    bio: 'Bakes too much bread, gives it away',
    colorClass: 'bg-sun',
    interests: ['food', 'talks'],
    location: offset(-0.9, 0.8),
    travelMode: 'walk',
    vibe: 'eager',
  },
  {
    id: 'p-aicha',
    name: 'Aïcha',
    age: 26,
    bio: 'Roofer by day, quiz menace by night',
    colorClass: 'bg-grape',
    interests: ['games', 'sports'],
    location: offset(1.6, -0.7),
    travelMode: 'transit',
    vibe: 'maybe',
  },
  {
    id: 'p-bo',
    name: 'Bo',
    age: 41,
    bio: 'Runs slow on purpose, talks fast',
    colorClass: 'bg-moss',
    interests: ['sports', 'outdoors'],
    location: offset(-1.8, 1.1),
    travelMode: 'bike',
    vibe: 'eager',
  },
  {
    id: 'p-ingrid',
    name: 'Ingrid',
    age: 58,
    bio: 'Retired electrician, fixes anything',
    colorClass: 'bg-clay',
    interests: ['talks', 'art'],
    location: offset(-0.4, -1.6),
    travelMode: 'walk',
    vibe: 'maybe',
  },
  {
    id: 'p-malik',
    name: 'Malik',
    age: 31,
    bio: 'Drives a tram, collects vinyl',
    colorClass: 'bg-sky',
    interests: ['music', 'talks'],
    location: offset(2.4, 1.9),
    travelMode: 'transit',
    vibe: 'eager',
  },
  {
    id: 'p-sena',
    name: 'Sena',
    age: 24,
    bio: 'Studies bees, dances salsa worse',
    colorClass: 'bg-berry',
    interests: ['dance', 'outdoors'],
    location: offset(1.1, 2.2),
    travelMode: 'bike',
    vibe: 'eager',
  },
  {
    id: 'p-paulo',
    name: 'Paulo',
    age: 37,
    bio: 'Chef on his day off, will still cook',
    colorClass: 'bg-sun',
    interests: ['food', 'games'],
    location: offset(-2.6, -1.2),
    travelMode: 'car',
    vibe: 'maybe',
  },
  {
    id: 'p-nour',
    name: 'Nour',
    age: 28,
    bio: 'Translator, four languages, one bike',
    colorClass: 'bg-grape',
    interests: ['talks', 'art'],
    location: offset(3.1, -0.9),
    travelMode: 'bike',
    vibe: 'maybe',
  },
  {
    id: 'p-kai',
    name: 'Kai',
    age: 22,
    bio: 'Apprentice carpenter, terrible at chess',
    colorClass: 'bg-moss',
    interests: ['games', 'sports'],
    location: offset(-3.4, 2.1),
    travelMode: 'transit',
    vibe: 'quiet',
  },
  {
    id: 'p-reva',
    name: 'Reva',
    age: 45,
    bio: 'Midwife, sings in a choir of strangers',
    colorClass: 'bg-sky',
    interests: ['music', 'talks'],
    location: offset(2.8, -3.4),
    travelMode: 'car',
    vibe: 'maybe',
  },
  {
    id: 'p-fabi',
    name: 'Fabi',
    age: 33,
    bio: 'Bike courier, knows every shortcut',
    colorClass: 'bg-clay',
    interests: ['sports', 'outdoors', 'food'],
    location: offset(-4.2, 1.4),
    travelMode: 'bike',
    vibe: 'eager',
  },
  {
    id: 'p-hana',
    name: 'Hana',
    age: 30,
    bio: 'Sound engineer, hears everything',
    colorClass: 'bg-berry',
    interests: ['music', 'art'],
    location: offset(4.6, 1.2),
    travelMode: 'transit',
    vibe: 'quiet',
  },
  {
    id: 'p-dmitri',
    name: 'Dmitri',
    age: 52,
    bio: 'Taxi driver, tells the good version',
    colorClass: 'bg-sun',
    interests: ['talks', 'games'],
    location: offset(-5.1, -2.6),
    travelMode: 'car',
    vibe: 'maybe',
  },
  {
    id: 'p-lea',
    name: 'Lea',
    age: 27,
    bio: 'Vet nurse, climbs on Tuesdays',
    colorClass: 'bg-grape',
    interests: ['sports', 'food'],
    location: offset(5.8, 2.9),
    travelMode: 'bike',
    vibe: 'maybe',
  },
  {
    id: 'p-jonas',
    name: 'Jonas',
    age: 39,
    bio: 'Postman, draws the routes he walks',
    colorClass: 'bg-moss',
    interests: ['art', 'outdoors'],
    location: offset(-6.4, 3.8),
    travelMode: 'walk',
    vibe: 'quiet',
  },
  {
    id: 'p-mira',
    name: 'Mira',
    age: 35,
    bio: 'Gardener, brings snacks to everything',
    colorClass: 'bg-sky',
    interests: ['outdoors', 'food', 'dance'],
    location: offset(7.2, -4.5),
    travelMode: 'car',
    vibe: 'eager',
  },
  {
    id: 'p-otto',
    name: 'Otto',
    age: 63,
    bio: 'Plays accordion at bus stops',
    colorClass: 'bg-clay',
    interests: ['music', 'talks'],
    location: offset(-8.1, -2.2),
    travelMode: 'transit',
    vibe: 'quiet',
  },
];

export const PEOPLE_BY_ID: Record<string, Person> = Object.fromEntries(
  PEOPLE.map((person) => [person.id, person]),
);

export const SPOTS_BY_ID: Record<string, Spot> = Object.fromEntries(
  SPOTS.map((spot) => [spot.id, spot]),
);
